# -*- coding: utf-8 -*-
"""TFM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vbMDlnQkAlZQ86p80mq9mv7Hr3B9Y8cS

# Autor: Daniela Déniz Viera

Esto es un TFM para encontrar cúmulos de estrellas mediante el algoritmo de aprendizaje no supervisado dbscan. Los datos que se van a utilizar son los proporcionados por Gaia, una misión de la ESA encargada de hacer un "mapa" de las estrellas de nuestra galaxia. En concreto en este TFM utilizaremos la base de datos del tercer release: Gaia DR3.

# Paquetes
"""

!pip install astroquery

!pip install hdbscan

# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from astroquery.gaia import Gaia
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.neighbors import NearestNeighbors
import hdbscan
from sklearn.metrics import silhouette_score
from hdbscan.validity import validity_index

"""# Descarga de datos

Lo primero que tendremos que hacer, es descagar los datos. Un módulo de python ha sido desarrollado para poder extraer datos de los data set de manera sencilla. En nustro caso, vamos a descargar datos centrándonos en regiones concretas del espacio, con el objetivo de hacer el problema computacionalmente más sencillo. Para ello vamos a utilizar una búsqueda en forma de "cono". Mediante el right ascencion y la declination describimos el punto central del cono y mediante el radio, el área que comprende ese cono de búsqueda.
"""

# función para descargar datos de Gaia DR3
def descargar_gaia_region(ra,dec,radio=2.0,g_max=18,parallax_min=None,parallax_max=None,max_rows=50000,output_csv=None):
    """
    Parámetros:
    - ra, dec: centro de la región(right ascension y declination).[deg]
    - radio_deg: radio del cono de la región. [deg]
    - g_max: magnitud máxima Gaia G.
    - parallax_min/parallax_max: filtros opcionales de paralaje. [mas](milisegundo de arco)
    - max_rows: número máximo de filas descargadas.
    """

    parallax_filter = ""

    if parallax_min is not None:
        parallax_filter += f" AND parallax >= {parallax_min}"

    if parallax_max is not None:
        parallax_filter += f" AND parallax <= {parallax_max}"

    query = f"""
    SELECT TOP {max_rows}
        source_id,ra,dec,
        parallax,parallax_error,
        pmra,pmra_error,
        pmdec,pmdec_error,
        phot_g_mean_mag,bp_rp,ruwe
    FROM gaiadr3.gaia_source
    WHERE
        1 = CONTAINS(
            POINT('ICRS', ra, dec),
            CIRCLE('ICRS', {ra}, {dec}, {radio}))
        AND parallax IS NOT NULL
        AND pmra IS NOT NULL
        AND pmdec IS NOT NULL
        AND phot_g_mean_mag < {g_max}
        AND ruwe < 1.4
        AND parallax_over_error > 5
        {parallax_filter}
    """

    job = Gaia.launch_job_async(query)
    table = job.get_results()

    df = table.to_pandas()

    if output_csv:
        df.to_csv(output_csv, index=False)

    return df

"""En la función anterior, preparamos un query para pedir datos a la base de datos de Gaia. Incluimos los siguientes parámetros en la query:
- Source_id : identificador único del objeto
- ra : nodo ascendente
- deg: declination
- pmra: movimiento propio en la dirección del nodo ascendente
- pmra_error: error estándar del movimiento propio en la dirección del nodo ascendente
- pmdec: movimiento propio en la dirección de la declinación
- pmdec: error estándar del movimiento propio en la dirección de la declinación
- phot_g_mean_mag: magnitud media en la banda G
- bp_rp : color bp_rp
- ruwe : magnitud global de error

Hemos escogido estas magnitudes por que son las más representativas sobre los cúmulos de estrellas que usarán nuestros algorítmos de clustering. Otras magnitudes nos sirven para comparar los resultados con observaciones astronómicas.
"""

# función para seleccionar variables concretas y obtener un subset de datos
def seleccionar_variables(df, variables):
    df_vars = df[variables].copy()
    df_vars = df_vars.dropna()

    return df_vars

"""Vamos ahora a descargar los datos de una región en concreto. Para ello, nos centraremos en la región conocida como las Pléyades. Cuyo centro es (56.75,24.12).A demás hemos elegido un radio de 3 grados al rededor de la región. Las Pleyádes se encuentran a unos 7 mas de distancia, por eso hemos elegido un paralaje mínimo de 5 mas y uno máximo de 10 mas."""

df = descargar_gaia_region(
    ra=56.75,
    dec=24.12,
    radio=3.0,
    g_max=18,
    parallax_min=5,
    parallax_max=10,
    output_csv="gaia_pleyades_region.csv")
print(df.shape)
print(df.head())

variable = ["ra", "dec", "parallax", "pmra", "pmdec"]
df_vars = seleccionar_variables(df, variable)
df_vars.head()

"""Hemos elegido estas features porque son las más representativas para identificar cúmulos de estrellas, el resto de variables que hemos pedido en la query las usaremos a modo de validación más adelante.

# Feature engineering / EDA

Antes de poder utilizar los datos en nuestros algoritmos de clustering, tenemos que transformar los datos, para que los algoritmos no se vean afectados debido a las irregularidades de estos. Los algoritmos de clustering, se basan mayoritariamente en la distancia entre los objetos que quiere clasificar. Nuestras variables, están en escalas completamente diferentes, pudiendo significar que las variables con mayor escala, pueden eclipsar al resto. Es por esto, que vamos a escalar las variables para que así sean utilizadas en igual medida por los algoritmos.

A demás, vamos hacer una análisis exploratorio de los datos para hacernos una idea de la forma que tienen nuestras variables, y así poder sacar conclusiones de valor para luego introducirlas en los algoritmos.
"""

# eda básico
df_vars.describe()

"""Arriba podemos ver un análisis estadístico básico de las variables que vamos a utilizar para identificar los cúmulos. Podemos ver que las variables tienen rangos bastante diferentes, por lo que más adelante tendremos que estandarizarlas. Por otro lado, vemos que los valores del nodo ascendente y de la declinación tienen sentido con respecto a lo que hemos pedido a través de la query. El paralaje también comprende el rango que hemos especificado en la query. En cuanto al movimiento propio, vemos que hay un rango bastante amplio de valores, ya que en general, el movimiento de las estrellas varía mucho.

Vamos ahora a apoyar las conclusiones que hemos sacado mediante la visualización de los datos en histogramas.
"""

def plot_histogramas(df):
    variables = ["ra","dec","parallax", "pmra", "pmdec"]
    titles = ["Nodo ascendente", "Declinación", "Paralaje", "PMra", "PMdec"]

    plt.figure(figsize=(15, 4))

    for i, var in enumerate(variables, 1):
        plt.subplot(1, 5, i)
        plt.title(titles[i-1])

        sns.histplot(
            df[var],
            bins=50,
            kde=True
        )
        plt.xlabel(var)

    plt.tight_layout()
    plt.show()

plot_histogramas(df_vars)

"""En los histogramas podemos ver los diferentes rangos de las variables. A demás también se observa un pico bastante pronunciado en todos los histogramas. Este pico coincide exactamente con la posición y la disancia del cúmulo Pléyades ya que los datos están centrados a su alrededor.

Una vez hecho esto, vamos a representar la posición en el cielo de las estrellas para ver cómo están distribuidas. Para ello representamos las coordenadas que describen su posición, es decir, el nodo ascendente y la declinación.
"""

plt.scatter(df["ra"], df["dec"], s=1)
plt.xlabel("Nodo ascendente [deg]")
plt.ylabel("Declinación [deg]")
plt.title("Distribución espacial")
plt.show()

"""Podemos ver  en el centro una región claramente densa. Otra forma de ver el cúmulo de una manera incluso más clara es representando su movimiento propio. Las estrellas de un cúmulo nacen a la vez, por lo que están ligadas gravitacionalmente, y esto hace que se muevan con velocidades muy similares."""

plt.scatter(df["pmra"], df["pmdec"], s=1)
plt.xlabel("pmRA [mas/yr]")
plt.ylabel("pmDEC [mas/yr]")
plt.title("Movimiento propio")
plt.show()

"""Vemos claramente un cúmulo.

Este gráfico representa un diagrama color–magnitud, aproximación observacional del diagrama de Hertzsprung-Russell diagram, donde se muestra la relación entre el color de las estrellas (bp_rp, indicador de su temperatura superficial) y su magnitud en la banda G. En este tipo de diagramas, las estrellas de un cúmulo abierto como las Pléyades tienden a distribuirse siguiendo una secuencia bien definida, conocida como secuencia principal, debido a que comparten edad, composición química y distancia, siendo la masa el principal factor diferenciador de sus propiedades físicas. Por el contrario, las estrellas de fondo, que pertenecen a distintas poblaciones estelares, aparecen más dispersas. Por tanto, este diagrama no solo permite analizar la estructura física de las estrellas, sino que constituye una herramienta fundamental para validar la pertenencia de las estrellas a un cúmulo tras aplicar algoritmos de clustering, ya que un conjunto real de miembros debe reproducir dicha secuencia característica.
"""

plt.scatter(
    df["bp_rp"],
    df["phot_g_mean_mag"],
    s=1
)

plt.gca().invert_yaxis()
plt.xlabel("BP - RP")
plt.ylabel("Magnitud G")
plt.title("Diagrama color-magnitud")
plt.show()

"""Pasamos ahora a hacer un feature engineering sencillo : limpieza de datos y estandarización."""

def comprobar_nulos(df, features):
    print(f"Valores nulos para la variable {features}:\n")
    print(df[features].isnull().sum())

for var in variable:
    comprobar_nulos(df_vars, var)

"""No tenemos ningún valor nulo. Era de esperar ya que el conjunto de datos de Gaia es por lo general de bastante calidad y muy limpio. Procedemos ahora a la estandarización de los datos, paso clave, ya que como hemos dicho antes nuestras variables están comprendidas en rangos bastante diferentes"""

def preparar_clustering(X):
    """
    Escala los datos para clustering.
    """

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    return X_scaled

X_scaled = preparar_clustering(df_vars)

"""# DBSCAN PLÉYADES

Vamos ahora a diseñar el modelo de DBSCAN. Lo primero será definir unos valores de epsilon y de MinPoints adecuados, ya que de ellos depende la buena performance de nuestro algoritmo. Como tenemos 5 features (dimensionalidad 5) un buen punto de partida para MinPoints será utilizar 10 (MinPoints = 2 x Dim). Una vez elegido el valor de MinPoints, tenemos que elegir el de epsilon. Para ello vamor a utilizar el método de la k-ésima distancia. Este método utiliza un valor de k inicial de MinPoints-1 (9 en nuestro caso). Después calcula la distancia al k-ésimo vecino más cercano a cada punto.Grafica las distancias ordenadas en el eje x, y el índice de los puntos ordenados en el y. Por último el epsilon se elige como el valor donde se aprecia un codo en la curva.
"""

def k_distance_plot(X_scaled, min_samples=10):
    """
    Calcula y representa el k-distance plot para DBSCAN.
    """

    # Modelo de vecinos
    neighbors = NearestNeighbors(n_neighbors=min_samples)
    neighbors_fit = neighbors.fit(X_scaled)

    # Distancias a los vecinos
    distances, indices = neighbors_fit.kneighbors(X_scaled)

    # Nos quedamos con la distancia al k-ésimo vecino
    k_distances = distances[:, min_samples - 1]

    # Ordenamos
    k_distances = np.sort(k_distances)

    # Plot
    plt.figure(figsize=(6, 5))
    plt.plot(k_distances, color="blue", linewidth=1)

    plt.xlabel("Puntos ordenados")
    plt.ylabel("Distancia al k-ésimo vecino")
    plt.title(f"K-distance plot (k = {min_samples})")

    plt.grid()
    plt.show()

    return k_distances

"""Añadimos también una función que nos permite calcular la silueta de los algoritmos, métrica que utilizaremos más tarde para comprobar la calidad de los resultados"""

# silueta
def calcular_silueta(X_scaled, labels):
    # Dos etiquetas como mínimo
    if len(set(labels)) < 2:
        return None

    return silhouette_score(X_scaled, labels)

k_distances = k_distance_plot(X_scaled, min_samples=10)

# función que evalua el modelo dbscan para un epsilon y minPoints dado
def modelo_dbscan(X_scaled, eps, min_samples):
    """
    Aplica DBSCAN sobre los datos escalados.
    """

    dbscan = DBSCAN(eps=eps,min_samples=min_samples)

    labels = dbscan.fit_predict(X_scaled)

    return labels, dbscan

# función para evaluar dbscan con diferentes valores de epsilon
def evaluar_dbscan(X_scaled, eps_values, min_samples=10):
    resultados = {}

    for eps in eps_values:
        labels, _ = modelo_dbscan(X_scaled,eps=eps,min_samples=min_samples)

        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
        n_ruido = np.sum(labels == -1)

        print(f"eps = {eps}")
        print(f"clusters detectados: {n_clusters}")
        print(f"puntos de ruido: {n_ruido}")
        print("-" * 30)

        resultados[eps] = labels

    return resultados

"""Viendo la gráfica del método de la k-ésima distancia, vemos que el codo se produce en torno a los valores de epsilon [1.5,2.0]. Vamos a evaluar nuestro modelo dbscan en torno a esos valores, para quedarnos con el que ofrece mejores resultados"""

eps_values = [1.5, 1.6, 1.7, 1.8, 1.9, 2.0]

resultados = evaluar_dbscan(
    X_scaled,
    eps_values,
    min_samples=10
)

"""Se observa que para valores de ε entre 1.5 y 2.0 el algoritmo DBSCAN detecta un único clúster correspondiente al cúmulo de las Pléyades, mientras que el número de puntos clasificados como ruido disminuye progresivamente al aumentar ε. Se selecciona un valor intermedio de ε que permite capturar la mayor parte de los miembros del cúmulo sin introducir una cantidad excesiva de estrellas de fondo.Epsilon = 1.7"""

labels, dbscan = modelo_dbscan(X_scaled,eps=1.7,min_samples=10)

df["cluster"] = labels

cluster_df = df[df["cluster"] == 0].copy()
ruido_df = df[df["cluster"] == -1].copy()
print("Número de estrellas en el cúmulo:", len(cluster_df))
print("Número de estrellas de ruido:", len(ruido_df))

plt.figure(figsize=(6,5))

plt.scatter(ruido_df["ra"],ruido_df["dec"],s=2,color="gray",label="Ruido")

plt.scatter(cluster_df["ra"],cluster_df["dec"],s=2,color="red",label="Cúmulo")

plt.xlabel("Nodo ascendente [deg]")
plt.ylabel("Declinación [deg]")
plt.title("Cúmulo detectado (posición)")
plt.legend()
plt.show()

plt.figure(figsize=(6,5))

plt.scatter(ruido_df["pmra"],ruido_df["pmdec"],s=2,color="gray")

plt.scatter(cluster_df["pmra"],cluster_df["pmdec"],s=2,color="red")

plt.xlabel("pmRA [mas/yr]")
plt.ylabel("pmDEC [mas/yr]")
plt.title("Movimiento propio")
plt.show()

plt.figure(figsize=(6,5))

plt.scatter(ruido_df["bp_rp"],ruido_df["phot_g_mean_mag"],s=2,color="gray")

plt.scatter(cluster_df["bp_rp"],cluster_df["phot_g_mean_mag"],s=2,color="red")

plt.gca().invert_yaxis()

plt.xlabel("BP - RP")
plt.ylabel("Magnitud G")
plt.title("Diagrama color-magnitud del cúmulo")
plt.show()

"""La validez del clustering obtenido mediante DBSCAN se confirma al analizar las propiedades físicas de las estrellas clasificadas como pertenecientes al cúmulo. En primer lugar, en el espacio de movimiento propio (pmRA–pmDEC) se observa una concentración compacta y bien definida, característica de una población estelar con movimiento común. En segundo lugar, la distribución espacial (RA–DEC) muestra una clara sobredensidad en la región central, coherente con la estructura de un cúmulo abierto. Finalmente, en el diagrama color–magnitud (HR), las estrellas identificadas siguen una secuencia principal bien definida, lo que indica homogeneidad en edad, distancia y composición. En conjunto, estos tres análisis confirman que DBSCAN ha logrado aislar correctamente los miembros del cúmulo frente al fondo estelar."""

print("Paralaje media:", cluster_df["parallax"].mean())
print("pmRA medio:", cluster_df["pmra"].mean())
print("pmDEC medio:", cluster_df["pmdec"].mean())

#silueta
silueta_dbscan_pleyades = calcular_silueta(X_scaled, labels)
silueta_dbscan_pleyades

"""# DBSCAN PERSEO

Con esto hemos validado con un caso sencillo nuestro modelo de DBSCAN. Vamos ahora a utilizar un caso un poco más complicado. La región de Perseo contiene dos cúmulos abiertos NGC 869 y NGC 884.
"""

df_perseo = descargar_gaia_region(
    ra=35.0,
    dec=57.0,
    radio=2.5,
    g_max=17,
    parallax_min=0.2,
    parallax_max=1.0,
    max_rows=30000,
    output_csv="perseo_doble_cumulo_gaia_dr3.csv"
)

variable = ["ra","dec","parallax", "pmra", "pmdec"]
df_vars = seleccionar_variables(df_perseo, variable)
df_vars.head()

# eda básico
df_vars.describe()

plot_histogramas(df_vars)

plt.scatter(df_perseo["ra"], df_perseo["dec"], s=1)
plt.xlabel("Nodo ascendente [deg]")
plt.ylabel("Declinación [deg]")
plt.title("Distribución espacial")
plt.show()

plt.scatter(df_perseo["pmra"], df_perseo["pmdec"], s=1)
plt.xlabel("pmRA [mas/yr]")
plt.ylabel("pmDEC [mas/yr]")
plt.title("Movimiento propio")
plt.show()

plt.scatter(df_perseo["bp_rp"],df_perseo["phot_g_mean_mag"],s=1)

plt.gca().invert_yaxis()
plt.xlabel("BP - RP")
plt.ylabel("Magnitud G")
plt.title("Diagrama color-magnitud")
plt.show()

for var in variable:
    comprobar_nulos(df_vars, var)

X_scaled = preparar_clustering(df_vars)

k_distances = k_distance_plot(X_scaled, min_samples=10)

eps_values = [1.3, 1.4, 1.5, 1.6, 1.7,1.8]
resultados = evaluar_dbscan(
    X_scaled,
    eps_values,
    min_samples=10
)

"""Vemos que dbscan tiene problemas para identificar clusters en conjuntos de datos con densidades significativamente diferentes. Vamos a desarrollar ahora un modelo de hdbscan, que fue desarrollado precisamente para solucionar este problema y poder especificar diferentes densidades dentro del mismo conjunto de datos.

# HDBSCAN PERSEO
"""

#modelo hdbscan
def modelo_hdbscan(X_scaled, min_cluster_size, min_samples):
    """
    Aplica HDBSCAN sobre los datos escalados.

    Parámetros:
    - min_cluster_size: tamaño mínimo de un cúmulo.
    - min_samples: controla lo conservador que es el algoritmo.

    Devuelve:
    - labels: etiquetas de los clusters (-1 es ruido)
    - probabilities: probabilidad de pertenencia al cluster
    - clusterer: modelo entrenado
    """

    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples
    )

    labels = clusterer.fit_predict(X_scaled)
    probabilities = clusterer.probabilities_

    return labels, probabilities, clusterer

"""Seleccionamos las mismas variables que utilizamos para estudiar el cúmulo de pleyades y escalamos los datos para una mejor interpretación del algoritmo."""

variable = ["ra", "dec", "parallax", "pmra", "pmdec"]

df_vars = seleccionar_variables(df_perseo, variable)

X_scaled = preparar_clustering(df_vars)

"""Se evaluaron varios valores de min_cluster_size, que controla el tamaño mínimo de las agrupaciones detectadas por HDBSCAN. Se seleccionó el valor que producía estructuras astrométricamente coherentes y estables. El parámetro min_samples se mantuvo fijo para reducir la complejidad del ajuste."
"""

def comparar_min_cluster_size(X_scaled, valores_min_cluster_size, min_samples=5):
    """
    Evalúa distintos valores de min_cluster_size para HDBSCAN.

    Para cada valor calcula:
    - número de clusters encontrados
    - número de puntos clasificados como ruido
    - porcentaje de ruido
    - tamaño de cada cluster

    Devuelve:
    - DataFrame con los resultados
    """

    resultados = []

    for mcs in valores_min_cluster_size:

        labels, probabilities, hdbscan_model = modelo_hdbscan(
            X_scaled,
            min_cluster_size=mcs,
            min_samples=min_samples
        )

        n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
        n_ruido = np.sum(labels == -1)
        porcentaje_ruido = n_ruido / len(labels) * 100

        tamaños_clusters = pd.Series(labels).value_counts().sort_index()

        resultados.append({
            "min_cluster_size": mcs,
            "min_samples": min_samples,
            "n_clusters": n_clusters,
            "n_ruido": n_ruido,
            "porcentaje_ruido": porcentaje_ruido,
            "tamaños_clusters": tamaños_clusters.to_dict()
        })

    return pd.DataFrame(resultados)

valores_min_cluster_size = [50, 80, 100, 150, 200]

resultados_hdbscan = comparar_min_cluster_size(
    X_scaled,
    valores_min_cluster_size=valores_min_cluster_size,
    min_samples=5
)

resultados_hdbscan

# ejecutamos modelo hbdscan
labels, probabilities, hdbscan_model = modelo_hdbscan(
    X_scaled,
    min_cluster_size=80,
    min_samples=5)

"""Estudiamos el número de clusters detectados por dbscan y el número de estrellas en cada uno de ellos."""

df_hdbscan = df_perseo.loc[df_vars.index].copy()

df_hdbscan["cluster_hdbscan"] = labels
df_hdbscan["prob_hdbscan"] = probabilities

n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
n_ruido = sum(labels == -1)

print("Clusters detectados:", n_clusters)
print("Puntos de ruido:", n_ruido)
print("Puntos totales:", len(df_hdbscan))

conteo_clusters = (
    df_hdbscan["cluster_hdbscan"]
    .value_counts()
    .sort_index()
)

print("\nNúmero de estrellas por cluster:")
print(conteo_clusters)

df_clusters = df_hdbscan[df_hdbscan["cluster_hdbscan"] != -1].copy()

print("\nNúmero de estrellas clasificadas en clusters:")
print(len(df_clusters))

resumen_clusters = df_clusters.groupby("cluster_hdbscan")[
    ["ra", "dec", "parallax", "pmra", "pmdec", "prob_hdbscan"]
    ].agg(["count", "mean", "std"])

print("\nResumen por cluster:")
print(resumen_clusters)

plt.figure(figsize=(6, 5))

plt.scatter(
    df_clusters["ra"],
    df_clusters["dec"],
    c=df_clusters["cluster_hdbscan"],
    s=3,
    cmap="tab10"
)

plt.xlabel("RA [deg]")
plt.ylabel("DEC [deg]")
plt.title("HDBSCAN: clusters detectados en posición")
plt.show()

plt.figure(figsize=(6, 5))

plt.scatter(
    df_clusters["pmra"],
    df_clusters["pmdec"],
    c=df_clusters["cluster_hdbscan"],
    s=3,
    cmap="tab10"
)

plt.xlabel("pmRA [mas/yr]")
plt.ylabel("pmDEC [mas/yr]")
plt.title("HDBSCAN: clusters en movimiento propio")
plt.show()

plt.figure(figsize=(6, 5))

plt.scatter(
    df_clusters["bp_rp"],
    df_clusters["phot_g_mean_mag"],
    c=df_clusters["cluster_hdbscan"],
    s=3,
    cmap="tab10"
)

plt.gca().invert_yaxis()
plt.xlabel("BP - RP")
plt.ylabel("Magnitud G")
plt.title("HDBSCAN: diagrama color-magnitud por cluster")
plt.show()

"""HDBSCAN permite identificar estructuras espacialmente coherentes que presentan además propiedades cinemáticas y fotométricas compatibles con cúmulos abiertos reales. A diferencia de DBSCAN, el algoritmo revela subestructuras internas y regiones de distinta densidad, proporcionando una representación más realista de la organización jerárquica del sistema estelar."""

df_clusters.groupby("cluster_hdbscan")[
    ["ra", "dec", "parallax", "pmra", "pmdec"]].mean()

"""Los centroides muestran que HDBSCAN identifica varias subestructuras con propiedades astrométricas diferenciadas. Los clusters 1 y 3 presentan valores similares de paralaje y movimiento propio, lo que sugiere que podrían estar asociados a las componentes principales del doble cúmulo de Perseo. Los clusters 0 y 2, aunque espacialmente próximos a la región analizada, muestran diferencias más claras en paralaje o posición, por lo que podrían corresponder a subestructuras, halo del sistema o contaminación residual del campo estelar."""

dbcv_hdbscan = validity_index(
    X_scaled.astype(np.float64),
    labels.astype(int)
)

print("DBCV HDBSCAN Perseo:", dbcv_hdbscan)